[project]
name = "syscovis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Silvan Stadelmann", email = "silvasta3@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rich>=14.1.0",
]

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"
